name: Ontology Pipeline

on:
  push:
    branches: [develop]

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Start Pipeline
        run: /home/stramp/run-ontology-pipeline.sh
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts

