name: Ontology Pipeline

on:
  push:
    branches: [develop]

jobs:
  ontology-pipeline:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Start Pipeline
        run: /home/stramp/run-ontology-pipeline.sh
      - uses: actions/upload-artifact@v2
        with:
          name: schema.ttl.dot.png
          path: artifacts/schema.ttl.dot.png
      - uses: actions/upload-artifact@v2
        with:
          name: schema.ttl.dot.svg
          path: artifacts/schema.ttl.dot.svg
      - uses: actions/upload-artifact@v2
        with:
          name: ZIP
          path: artifacts/*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts

